name: Azure Python 3.9
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            make install
        - name: Lint
          run: |
            make lint
        - name: Run Tests
          run: |
            make test